# Generated by Django 5.2.5 on 2025-09-04 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dre",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código da DRE"),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome da DRE")),
                ("sigla", models.CharField(max_length=50, verbose_name="Sigla da DRE")),
            ],
            options={
                "verbose_name": "DRE",
                "verbose_name_plural": "DREs",
                "db_table": "dres",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Escolha",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Escolha"),
                ),
            ],
            options={
                "verbose_name": "Escolha",
                "verbose_name_plural": "Escolhas",
                "db_table": "escolhas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "codigo_eol",
                    models.CharField(max_length=20, verbose_name="Código EOL"),
                ),
                (
                    "nome_oficial",
                    models.CharField(max_length=255, verbose_name="Nome Oficial"),
                ),
                (
                    "nome_nao_oficial",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome Não Oficial",
                    ),
                ),
                (
                    "tipo_unidade_admin",
                    models.CharField(
                        max_length=255, verbose_name="Tipo Unidade Administrativa"
                    ),
                ),
                ("tipo_ue", models.CharField(max_length=255, verbose_name="Tipo UE")),
                (
                    "logradouro",
                    models.CharField(max_length=255, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="Número")),
                ("bairro", models.CharField(max_length=255, verbose_name="Bairro")),
                ("cep", models.IntegerField(verbose_name="CEP")),
                ("distrito", models.CharField(max_length=255, verbose_name="Distrito")),
                (
                    "sub_prefeitura",
                    models.CharField(max_length=255, verbose_name="Subprefeitura"),
                ),
                (
                    "nome_dre",
                    models.CharField(max_length=255, verbose_name="Nome da DRE"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "telefone1",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Telefone 1"
                    ),
                ),
                (
                    "telefone2",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Telefone 2"
                    ),
                ),
                (
                    "ano_construcao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Construção"
                    ),
                ),
                (
                    "propriedade",
                    models.CharField(max_length=50, verbose_name="Propriedade"),
                ),
                (
                    "capacidade_vagas_matutino",
                    models.IntegerField(
                        default=0, verbose_name="Capacidade Vagas Matutino"
                    ),
                ),
                (
                    "capacidade_vagas_vespertino",
                    models.IntegerField(
                        default=0, verbose_name="Capacidade Vagas Vespertino"
                    ),
                ),
                (
                    "capacidade_vagas_noturno",
                    models.IntegerField(
                        default=0, verbose_name="Capacidade Vagas Noturno"
                    ),
                ),
                (
                    "capacidade_vagas_intermediario",
                    models.IntegerField(
                        default=0, verbose_name="Capacidade Vagas Intermediário"
                    ),
                ),
                (
                    "capacidade_vagas_integral",
                    models.IntegerField(
                        default=0, verbose_name="Capacidade Vagas Integral"
                    ),
                ),
                (
                    "capacidade_vagas_total",
                    models.IntegerField(
                        default=0, verbose_name="Capacidade Vagas Total"
                    ),
                ),
                (
                    "organizacao_parceira",
                    models.BooleanField(
                        default=False, verbose_name="Organização Parceira"
                    ),
                ),
                (
                    "quantidade_de_funcionarios",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade de Funcionários"
                    ),
                ),
                ("status", models.CharField(max_length=30, verbose_name="Status")),
                (
                    "dre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escolhas.dre",
                        verbose_name="DRE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
                "db_table": "escolas",
                "ordering": ["nome_oficial"],
            },
        ),
    ]
