# Generated by Django 5.2.5 on 2025-09-01 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escolha",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Escolha"),
                ),
            ],
            options={
                "verbose_name": "Escolha",
                "verbose_name_plural": "Escolhas",
                "db_table": "escolhas",
                "ordering": ["nome"],
            },
        ),
    ]
