# Generated by Django 5.2.5 on 2025-09-01 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0002_escolha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concurso",
            name="cargos",
        ),
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.DeleteModel(
            name="Concurso",
        ),
    ]
