# Generated by Django 5.2.5 on 2025-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0005_vagasescolaslote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagasescolas",
            name="vagas_definitivas_utilizadas",
            field=models.IntegerField(
                default=0, verbose_name="Vagas Definitivas Utilizadas"
            ),
        ),
        migrations.AddField(
            model_name="vagasescolas",
            name="vagas_precarias_utilizadas",
            field=models.IntegerField(
                default=0, verbose_name="Vagas Precárias Utilizadas"
            ),
        ),
    ]
