# Generated by Django 5.2.5 on 2025-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0007_alter_escola_cep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vagasescolas",
            name="vagas_definitivas_utilizadas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vagas Definitivas Utilizadas"
            ),
        ),
        migrations.AlterField(
            model_name="vagasescolas",
            name="vagas_precarias_utilizadas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vagas Precárias Utilizadas"
            ),
        ),
    ]
