# Generated by Django 5.2.5 on 2025-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0009_vagasescolas_foi_utilizada"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagasescolas",
            name="esta_checada",
            field=models.BooleanField(default=True, verbose_name="Está Checada"),
        ),
    ]
