# Generated by Django 5.2.5

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0011_alter_escolha_options_remove_escolha_nome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoEscolha",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "escolha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="escolhas.escolha",
                        verbose_name="Escolha",
                    ),
                ),
                (
                    "situacao_anterior",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Situação Anterior",
                    ),
                ),
                (
                    "situacao_nova",
                    models.CharField(
                        max_length=20, verbose_name="Situação Nova"
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Escolha",
                "verbose_name_plural": "Históricos de Escolhas",
                "db_table": "historico_escolhas",
                "ordering": ["-criado_em"],
            },
        ),
    ]

