# Generated by Django 5.2.5 on 2025-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0012_historicoescolha"),
    ]

    operations = [
        migrations.AddField(
            model_name="escolha",
            name="concurso_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID do Concurso"
            ),
        )
    ]
