# Generated by Django 5.2.5 on 2025-12-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0013_escolha_concurso_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicoescolha",
            name="situacao_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("escolha", "Escolha"),
                    ("nao-escolha", "Não escolha"),
                    ("reconvocacao", "Reconvocação"),
                ],
                max_length=20,
                null=True,
                verbose_name="Situação Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="historicoescolha",
            name="situacao_nova",
            field=models.CharField(
                choices=[
                    ("escolha", "Escolha"),
                    ("nao-escolha", "Não escolha"),
                    ("reconvocacao", "Reconvocação"),
                ],
                max_length=20,
                verbose_name="Situação Nova",
            ),
        ),
    ]
