# Generated by Django 5.2.5 on 2025-12-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0013_escolha_concurso_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagasescolas",
            name="vagas_definitivas_restantes",
            field=models.IntegerField(
                default=0, verbose_name="Vagas Definitivas Restantes"
            ),
        ),
        migrations.AddField(
            model_name="vagasescolas",
            name="vagas_precarias_restantes",
            field=models.IntegerField(
                default=0, verbose_name="Vagas Precárias Restantes"
            ),
        ),
        migrations.AlterField(
            model_name="historicoescolha",
            name="situacao_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("escolha", "Escolha"),
                    ("nao-escolha", "Não escolha"),
                    ("reconvocacao", "Reconvocação"),
                ],
                max_length=20,
                null=True,
                verbose_name="Situação Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="historicoescolha",
            name="situacao_nova",
            field=models.CharField(
                choices=[
                    ("escolha", "Escolha"),
                    ("nao-escolha", "Não escolha"),
                    ("reconvocacao", "Reconvocação"),
                ],
                max_length=20,
                verbose_name="Situação Nova",
            ),
        ),
    ]
