# Generated by Django 5.2.5 on 2026-01-20 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0016_merge_20260120_1205"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametrizacao",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "tipo_ue",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Tipo UE",
                    ),
                ),
                (
                    "usar",
                    models.BooleanField(
                        default=False, verbose_name="Utilizar este tipo de UE"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametrização de Tipo UE",
                "verbose_name_plural": "Parametrizações de Tipos UE",
                "db_table": "escolhas_parametrizacao",
                "ordering": ["tipo_ue"],
            },
        ),
    ]
