# Generated by Django 5.2.5 on 2026-03-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0017_parametrizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="escola",
            name="codigo_integracao",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código Integração"
            ),
        ),
    ]
