# Generated by Django 5.2.5 on 2025-09-10 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VagasEscolas",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "data_fechamento_modulo",
                    models.DateField(verbose_name="Data de Fechamento do Módulo"),
                ),
                ("cargo_codigo", models.IntegerField(verbose_name="Código do Cargo")),
                (
                    "cargo_descricao",
                    models.CharField(max_length=200, verbose_name="Descrição do Cargo"),
                ),
                (
                    "vagas_precarias",
                    models.IntegerField(default=0, verbose_name="Vagas Precárias"),
                ),
                (
                    "vagas_definitivas",
                    models.IntegerField(default=0, verbose_name="Vagas Definitivas"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("suspenso", "Suspenso"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas_escolas",
                        to="escolhas.escola",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vagas da Escola",
                "verbose_name_plural": "Vagas das Escolas",
                "db_table": "vagas_escolas",
                "ordering": ["-data_fechamento_modulo", "escola__nome_oficial"],
            },
        ),
    ]
