# Generated by Django 5.2.5 on 2025-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0002_vagasescolas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vagasescolas",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Ativo"),
                    ("0", "Inativo"),
                    ("2", "Suspenso"),
                    ("3", "Cancelado"),
                ],
                default="1",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
