# Generated by Django 5.2.5 on 2025-09-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0003_alter_vagasescolas_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagasescolas",
            name="concurso_nome",
            field=models.CharField(
                blank=True,
                help_text="Nome do concurso relacionado (opcional)",
                max_length=255,
                null=True,
                verbose_name="Nome do concurso",
            ),
        ),
        migrations.AddField(
            model_name="vagasescolas",
            name="concurso_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="UUID do concurso relacionado (opcional)",
                null=True,
                verbose_name="UUID do concurso",
            ),
        ),
        migrations.AddIndex(
            model_name="vagasescolas",
            index=models.Index(
                fields=["concurso_uuid"], name="vagas_escol_concurs_ad6a5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vagasescolas",
            index=models.Index(
                fields=["concurso_nome"], name="vagas_escol_concurs_ca6ca6_idx"
            ),
        ),
    ]
