# Generated by Django 5.2.5 on 2025-10-01 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0004_vagasescolas_concurso_nome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VagasEscolasLote",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("processo_uuid", models.UUIDField(verbose_name="UUID do Processo")),
                (
                    "processo_nome",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Processo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Vagas do Processo",
                "verbose_name_plural": "Lotes de Vagas dos Processos",
                "db_table": "vagas_escolas_lote",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.RemoveIndex(
            model_name="vagasescolas",
            name="vagas_escol_concurs_ad6a5a_idx",
        ),
        migrations.RemoveIndex(
            model_name="vagasescolas",
            name="vagas_escol_concurs_ca6ca6_idx",
        ),
        migrations.RemoveField(
            model_name="vagasescolas",
            name="concurso_nome",
        ),
        migrations.RemoveField(
            model_name="vagasescolas",
            name="concurso_uuid",
        ),
        migrations.AddField(
            model_name="vagasescolas",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vagas",
                to="escolhas.vagasescolaslote",
                verbose_name="Lote do Processo",
            ),
        ),
    ]
