# Generated by Django 5.2.5 on 2025-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0006_vagasescolas_vagas_definitivas_utilizadas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escola",
            name="cep",
            field=models.CharField(max_length=20, verbose_name="CEP"),
        ),
    ]
