# Generated by Django 5.2.5 on 2025-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0008_alter_vagasescolas_vagas_definitivas_utilizadas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagasescolas",
            name="foi_utilizada",
            field=models.BooleanField(default=False, verbose_name="Foi Utilizada"),
        ),
    ]
