# Generated by Django 5.2.5 on 2025-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0010_vagasescolas_esta_checada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escolha",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Escolha",
                "verbose_name_plural": "Escolhas",
            },
        ),
        migrations.RemoveField(
            model_name="escolha",
            name="nome",
        ),
        migrations.AddField(
            model_name="escolha",
            name="candidato_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID do Candidato"
            ),
        ),
        migrations.AddField(
            model_name="escolha",
            name="e_retardatario",
            field=models.BooleanField(default=False, verbose_name="É retardatário"),
        ),
        migrations.AddField(
            model_name="escolha",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("escolha", "Escolha"),
                    ("nao-escolha", "Não escolha"),
                    ("reconvocacao", "Reconvocação"),
                ],
                default="escolha",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.AddField(
            model_name="escolha",
            name="tipo_vaga",
            field=models.CharField(
                blank=True,
                choices=[("definitiva", "Definitiva"), ("precaria", "Precária")],
                max_length=20,
                null=True,
                verbose_name="Tipo de Vaga",
            ),
        ),
        migrations.AddField(
            model_name="escolha",
            name="vaga_escola_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID da Vaga da Escola"
            ),
        ),
    ]
