# Generated by Django 5.2.5 on 2026-01-20 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0014_alter_historicoescolha_situacao_anterior_and_more"),
        ("escolhas", "0015_convert_vaga_escola_uuid_to_fk"),
    ]

    operations = []
