# Generated by Django 5.2.5 on 2026-06-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolhas", "0018_add_escola_codigo_integracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagasescolaslote",
            name="concurso_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID do Concurso"
            ),
        ),
    ]
